### ISSUE TITLE
Select all jobs at once from the dashboard

### ISSUE THREAD

**Issue by Sulivan1999** [pschlan/cron-job.org#242]
Hello!

Would it be possible to create an option to select all jobs at once, directly on the panel?

When we need to delete or deactivate multiple jobs, we need to select them one by one and then do the action. When there are many jobs this becomes a bit tiring, the option to select them all would be interesting.

**Comment by pschlan** [comment]
Good point. Let me see what I can do.

**Comment by kleenkanteen** [comment]
Saw the same use case myself except to delete cron jobs I made when testing.

@pschlan Could I pick up this task? And any idea on how hard it is?

**Comment by pschlan** [comment]
Of course, feel free to work on it. That would be awesome.

**Comment by kleenkanteen** [comment]
I tried running the repo in a github codespace (smallest one with 8gb ram). I made a devcontainer from the provided Dockerfile. It uses Ubuntu 20.04 LTS.

I followed the steps on [https://github.com/pschlan/cron-job.org?tab=readme-ov-file#example-environment-using-docker-compose](https://github.com/pschlan/cron-job.org?tab=readme-ov-file#example-environment-using-docker-compose) but on step 4 with `docker compose up`, I get this error, posting as a gist because it is so long: [https://gist.github.com/kleenkanteen/819ca0e714875dc955513f801eb7f19c](https://gist.github.com/kleenkanteen/819ca0e714875dc955513f801eb7f19c)

Any idea why it isn't builiding?

**Comment by pschlan** [comment]
I have never seen this. It might be running out of memory, can you try to assign more RAM, even if just for building?

**Comment by kleenkanteen** [comment]
Doubling the ram fixed the issue. All services started now and showing logs in terminal. Although I get this log showing up:
`chronos-1       | Chronos runtime error: MySQL_DB::connect(): Unknown MySQL server host 'mysql-node' (2)`

**Comment by kleenkanteen** [comment]
I'm unable to create an account after opening up the frontend.

**Comment by pschlan** [comment]
> Doubling the ram fixed the issue. All services started now and showing logs in terminal. Although I get this log showing up: `chronos-1 | Chronos runtime error: MySQL_DB::connect(): Unknown MySQL server host 'mysql-node' (2)`

That's not unusual during startup phase. It should retry and eventually succeed.

> I'm unable to create an account after opening up the frontend. Status of 500 from http://127.0.0.1:8010/api/ when clicking create account.

Did you set a valid SMTP_SERVER which accepts emails?

**Comment by kleenkanteen** [comment]
> That's not unusual during startup phase. It should retry and eventually succeed.

Looking at the terminal it keeps on happening.

> Did you set a valid SMTP_SERVER which accepts emails?
Nope. Easiest way to do it?

Here is what I see upon running docker compose up: https://gist.github.com/kleenkanteen/927e6a66a5d51c5eaa94fa7c94d487c6

**Comment by kleenkanteen** [comment]
I added this to docker-compose.yml:
```
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail-server
    # example.com should be replaced with the own domain for the mail server:
    ports:
        - "25:25"
        - "587:587"
        - "465:465"
    volumes:
        - ./docker-data/dms/mail-data/:/var/mail/
        - ./docker-data/dms/mail-state/:/var/mail-state/
        - ./docker-data/dms/mail-logs/:/var/log/mail/
        - ./docker-data/dms/config/:/tmp/docker-mailserver/
        # Path should be adjusted accordingly:
        - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/
        - /etc/localtime:/etc/localtime:ro
    environment:
        - ENABLE_FAIL2BAN=1
        # If letsencrypt for SSL/TLS certificate is used (otherwise adapt)
        - SSL_TYPE=letsencrypt
        - PERMIT_DOCKER=network
        - ONE_DIR=1
        - ENABLE_POSTGREY=0
        - ENABLE_CLAMAV=0
        - ENABLE_SPAMASSASSIN=0
        - SPOOF_PROTECTION=0
    cap_add:
        - NET_ADMIN # For Fail2Ban to work
        - SYS_PTRACE
```
and  in .env changed this line:
`SMTP_SERVER=http://${CJO_DOMAIN}:25`

Still upon creating an account, I get a 500 server error.
